version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_DB: hyperloop
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
    volumes:
      - ./temp/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      KAFKA_ENABLE_KRAFT: 'yes'
      KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CFG_LISTENERS: 'PLAINTEXT://:9092,CONTROLLER://:9094'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_CFG_BROKER_ID: '1'
      KAFKA_NODE_ID: '1'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9094'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    ports:
      - "9092:9092"

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: 'kafka:9092'
      KAFKA_CLUSTERS_0_NAME: 'default'
    ports:
      - "8080:8080"
